-- Rupert Cloud Core v0.10
-- Private state lives in Supabase, never in the public GitHub repository.

create extension if not exists pgcrypto;

create table if not exists public.rupert_memory (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'note',
  title text not null,
  content text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rupert_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null default 'default',
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.rupert_settings (
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create table if not exists public.rupert_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  source text not null,
  action_name text not null,
  risk text not null check (risk in ('read','write','destructive','reasoning')),
  status text not null check (status in ('allowed','denied','completed','failed')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists rupert_memory_user_updated_idx on public.rupert_memory(user_id, updated_at desc);
create index if not exists rupert_messages_user_session_idx on public.rupert_messages(user_id, session_id, created_at desc);
create index if not exists rupert_audit_user_created_idx on public.rupert_audit(user_id, created_at desc);

create or replace function public.rupert_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rupert_memory_touch on public.rupert_memory;
create trigger rupert_memory_touch before update on public.rupert_memory
for each row execute function public.rupert_touch_updated_at();

drop trigger if exists rupert_settings_touch on public.rupert_settings;
create trigger rupert_settings_touch before update on public.rupert_settings
for each row execute function public.rupert_touch_updated_at();

alter table public.rupert_memory enable row level security;
alter table public.rupert_messages enable row level security;
alter table public.rupert_settings enable row level security;
alter table public.rupert_audit enable row level security;

create policy "memory own rows" on public.rupert_memory
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "messages own rows" on public.rupert_messages
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "settings own rows" on public.rupert_settings
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "audit own rows" on public.rupert_audit
for select using (auth.uid() = user_id);

create policy "audit insert own rows" on public.rupert_audit
for insert with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('rupert-private', 'rupert-private', false)
on conflict (id) do update set public = false;

create policy "rupert private storage read" on storage.objects
for select using (
  bucket_id = 'rupert-private'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "rupert private storage write" on storage.objects
for insert with check (
  bucket_id = 'rupert-private'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "rupert private storage update" on storage.objects
for update using (
  bucket_id = 'rupert-private'
  and (storage.foldername(name))[1] = auth.uid()::text
) with check (
  bucket_id = 'rupert-private'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "rupert private storage delete" on storage.objects
for delete using (
  bucket_id = 'rupert-private'
  and (storage.foldername(name))[1] = auth.uid()::text
);
